### PR TITLE
(WIP) Roadmap to version 2

### PR DESCRIPTION
**Pull request by firstred**
> Due to changes in the PostNL API, the original 2.0 plans have been canceled and are superseded by the following roadmap:

## New version:
- [x] Update min. PHP version to 7.1
- [x] Migrate to the Labeling webservice v2.2 (Jan 25, 2019)
- [x] Migrate to the Confirming webservice v2.0 (Jan 25, 2019)
- [x] Remove XML (`sabre/xml`) support (no longer needed for a REST-only package)
- [x] Remove the legacy SOAP API, which by now has been taken offline
- [x] Remove the new SOAP API, which will be taken offline
- [x] Fully migrate to Symfony code style
- [x] Replace SOAP-inspired object structure with its REST counterpart
- [x] Simplify Request and Response objects, one per service and request/response
  - [x] Request object => [PSR-7](https://www.php-fig.org/psr/psr-7/) Request (e.g. `CalculateShippingDateRequest` request object)
  - [x] [PSR-7](https://www.php-fig.org/psr/psr-7/) response => Response object (e.g. `CalculateShippingDateResponse` response object)
- [x] Use [PSR-17](https://www.php-fig.org/psr/psr-17/) factories for Requests and Responses
- [x] Support [PSR-11](https://www.php-fig.org/psr/psr-11/) Dependency Injection Containers
  - [x] [PHP-DI dependency injection](https://php-di.org/)
  - [x] [Symfony dependency injection](https://symfony.com/doc/current/components/dependency_injection.html)
  - ~~Laravel~~ (under investigation)
- [ ] Add integration tests
- [x] Support Smart Returns (Printerloos retourneren)
- [x] Postal code API
- [x] Use [HTTPlug](https://github.com/php-http/httplug) so this package can use any HTTP client. Support Both [PSR-18](https://www.php-fig.org/psr/psr-18/) and async clients.
- ~~New checkout API (beta)~~ Redundant
- ~~Adrescheck Nationaal~~ Seems to have been discontinued
- ~~Adrescheck Basis Nationaal~~ Seems to have been discontinued
- ~~Adrescheck Internationaal~~ Seems to have been discontinued
- ~~Geo Adrescheck Nationaal~~ Seems to have been discontinued
- ~~IBANcheck nationaal~~ Seems to have been discontinued
- ~~Bedrijfscheck Nationaal~~ Seems to have been discontinued
- ~~Kredietcheck Zakelijk~~ Seems to have been discontinued
- ~~Support Return on Demand webservice v1.0 (Oct 1, 2018)~~ Still missing the proper API key it seems, would love to add this feature if possible. Please reply to this topic if you have successfully used this feature!

## Original plans:

- Update min. PHP version to 7.1
- Migrate to the Labeling webservice v2.2 (Jan 25, 2019)
- Migrate to the Confirming webservice v2.0 (Jan 25, 2019)
- Update main XML (`sabre/xml`) package to a more stable version
- Remove the legacy SOAP API, which by now has been taken offline
- Fully migrate to Symfony code style
- Add integration tests
- ~~Support Return on Demand webservice v1.0 (Oct 1, 2018) [REST only]~~ Missing API key and documentation

### CODE REVIEW

**Comment by TomKriek** [comment]
@firstred Any news on when this PR might go through and we get a new tagged release?

**Comment by firstred** [comment]
Not yet. I've had to cancel most of this project due to PostNL dropping support for the SOAP sometime in the future. Besides, the REST version seems to already provide more features and turned out to be a lot more stable than SOAP.

This is a great opportunity to fully focus on the new API and simplify the library itself, so I am going to cancel the current 2.0 plans and replace it with something totally new before the busy season (probably 1st of September).

**Comment by firstred** [comment]
I just updated the roadmap, please open a new issue if you'd like to see any changes.

**Comment by andheiberg-gelato** [comment]
Any updates on this?

**Comment by firstred** [comment]
I was unable to release 2.0 due to the ever changing APIs. Currently, I am looking for a way to release a 3.0 that doesn't include the improperly documented APIs, such as:
- Adrescheck Nationaal
- Adrescheck Basis Nationaal
- Adrescheck Internationaal
- Geo Adrescheck Nationaal
- IBANcheck nationaal Seems to have been discontinued
- Bedrijfscheck Nationaal
- Kredietcheck Zakelijk
but still has all the basics needed for shipping with PostNL.

This way we should be able to keep up with rapid changes in the newer REST API.

Also, the included serializer and SOAP API turned out to be much of a burden to support. Removing support for the SOAP API was already on the roadmap, due to it being phased out soon.

I am currently testing Symfony's Serializer to see if that might be a good fit to replace the serializer for the REST API. One of the reasons I chose Symfony's over the incredibly popular [JMS Serializer](https://jmsyst.com/libs/serializer) is because of the extended support period offered by Symfony and their history of making changes in a backward-compatible way.
Once this has been finished I think we can take the pieces from version 2.0 and place them in a new version, 3.0.

As soon as I have the results from the migration to a new serializer, I'll update this PR. I'm unable to give any deadlines, as I have only just started to pick up personal projects again since the COVID-19 outbreak.

**Comment by andheiberg-gelato** [comment]
@firstred thank you for the update 👌and all the hard work on this project.

**Comment by TomKriek** [comment]
I've been looking around a bit in the v2.0.0 version but it seems like the complete package will be unusable without Symfony DI. This seems to completely break the previous way of using the package by quite a lot. Is there any plan to make this more usable without being overly dependant on a framework like symfony?

**Comment by firstred** [comment]
That's a good point. I tried to avoid a hard-coded dependency on Symfony's DI by supporting any PSR-11 container implementation. It is possible to use PHP-DI as well.

But like you mentioned, this indeed breaks the previous way of using this package. It's not possible to use multiple API keys for example.
I'm currently trying to figure out an easier way to wire the library, so it should still be easy to integrate it into a Symfony bundle and a Laravel package (which is what I am trying to accomplish). A stand-alone factory could then be added to this library to both restore the previous way of using it (`new Postnl(…)`) and remove the dependency on a PSR-11 container in its entirety.

**Comment by firstred** [comment]
> I've been looking around a bit in the v2.0.0 version but it seems like the complete package will be unusable without Symfony DI. This seems to completely break the previous way of using the package by quite a lot. Is there any plan to make this more usable without being overly dependant on a framework like symfony?

**Pull request closed without merging**
